### ISSUE TITLE
installed pip, for example hg,  not found

### ISSUE THREAD

**Issue by a4z** [tuvistavie/asdf-python#12]
using this asdf pluging , run 
`pip install mercurial`
hg is installed, but can not be executed since it is not in PATH
bit it is in ~/.asdf/installs/python/2.7.13/bin

**Comment by tuvistavie** [comment]
Run `asdf reshim python` so that the shim is added to `~/.asdf/shims`

**Comment by a4z** [comment]
That did the trick, thanks!
