### ISSUE TITLE
Can't install packages on Ubuntu

### ISSUE THREAD

**Issue by Trevoke** [tuvistavie/asdf-python#17]
Looks like `pip` tries to install to the system python package directory instead of the asdf directory. Kind of defeats the purpose.

**Comment by tuvistavie** [comment]
Did you try `asdf reshim python` after installing?

**Comment by Trevoke** [comment]
Ooh, yes, that worked (I think).

I had gotten it to work by typing the full path to the asdf pip executable; with other packages it seems I don't need to manually reshim, and when I did a `which pip` it seemed to show the correct path, so I didn't think it was necessary.
