### ISSUE TITLE
It doesn't work on Mac

### ISSUE THREAD

**Issue by zhaoyi0113** [tuvistavie/asdf-python#24]
I am using Mac High Sierra and I couldn't use asdf for python at all. Below is the versions of python I have installed:
```
$ asdf list python
2.7
3.5
3.6.3
3.6
```
when I change to 3.6 as blow I couldn't run python command:

```
$ asdf global python 3.6
$ which python
/Users/joey/.asdf/shims/python
$ python --version
No such command in 3.6 of python
```
I always get `No such command xx of python` for every version of python.  Is there any other configuration I need to make?

**Comment by kalbir** [comment]
Running `asdf reshim python` solved this for me.

**Comment by chulkilee** [comment]
I opened a new shell and then it worked.

**Comment by tuvistavie** [comment]
I will close for now, please comment if you still have issues.
