### ISSUE TITLE
Support / bundling pipenv

### ISSUE THREAD

**Issue by cLupus** [tuvistavie/asdf-python#26]
Hi,
Is there any plans of integrating [pipenv](https://github.com/pypa/pipenv) into the plugin?

**Comment by tuvistavie** [comment]
Hi,
I do not have any plans to add pipenv integration, but would gladly accept PRs.
Thank you.

**Comment by omares** [comment]
Hey, i am evaluating if i should switch to asdf and its various plugins and would like to know if pipenv works in conjunction with asdf-python or do the tools conflict with each other?

**Comment by cLupus** [comment]
My experience is that pipenv works well with asdf.
The prgamatic way of installing pipenv, is `pip install pipenv`, and as long as you ensure that the you are careful with which version of python you use.

Note that Pipenv is set to be the de facto standard, and when the Pipfile format is finalized, it seems likely that pipenv will come with python as standard.

**Comment by tuvistavie** [comment]
I have now been using pipenv for a little while and it works perfectly with asdf-python, so I will close here.
Please comment or open a new issue if you run into issues related to pipenv.
Thanks.

**Comment by ianliu** [comment]
@tuvistavie I've installed pipenv with `pip install pipenv`, but when I issue `pipenv` it is not recognized as a command. Any hints why this is happening?
Here is some info that might help:
```bash
ls ~/.asdf/installs/python/3.7.0/bin/pipenv # OK
ls ~/.asdf/shims/pipenv # File does not exist
```

**Comment by ianliu** [comment]
Oh, sorry, I guess I just needed to call `asdf reshim python 3.7.0`. Thanks

**Comment by and-semakin** [comment]
https://github.com/asdf-vm/asdf/issues/269 is now resolved.
