### ISSUE TITLE
Installing binaries using the bundled pip

### ISSUE THREAD

**Issue by Qqwy** [tuvistavie/asdf-python#28]
I am trying to install [flask](http://flask.pocoo.org/). It itself installs fine when running `pip install flask`, but I cannot figure out how to run the binary that it is supposed to install as well (The `FLASK_APP=hello.py flask run` command does not work, because the `flask` binary cannot be found).

Where does asdf-python install the binaries to? Do I need to add some directory to my PATH?

**Comment by tuvistavie** [comment]
`asdf reshim python` should make your binary available.

**Comment by Qqwy** [comment]
Works wonderfully!
