### ISSUE TITLE
error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by johnhamelink** [tuvistavie/asdf-python#3]
Hi there!

```
asdf plugin-add python https://github.com/tuvistavie/asdf-python.git
asdf install python 2.7.9
asdf local python 2.7.9
asdf reshim python 2.7.9
python -v
```

Produces:

```
/home/john/.asdf/installs/python/2.7.9/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

I'm sticking to using Arch's python, python-pip, python2, and python2-pip packages for now but I'd like to use asdf instead.

I'm not sure what other info you might need so let me know!

**Comment by tuvistavie** [comment]
Hi, thanks for reporting.
I think I ran in the same issue, but I completely forgot how I solved this,
I am going to take a look!

**Comment by johnhamelink** [comment]
Thanks @tuvistavie 🚀

**Comment by DavidAntaramian** [comment]
Just ran into this issue trying to run `pip3` with version `3.6.0`.

Running it this way seems to fix it:

**Comment by tuvistavie** [comment]
The plugin is now a wrapper around python-build, so I think this should be fixed.
Please let me know if it works for you, thanks!

**Comment by johnhamelink** [comment]
Yep this is fixed, thanks! :)

**Comment by tuvistavie** [comment]
Great, closing the issue!
