### ISSUE TITLE
No such command in 3.6.4 of python on "clear" command.

### ISSUE THREAD

**Issue by qwexvf** [tuvistavie/asdf-python#31]
After installing and doing "asdf global or local python 3.6.4" then if i do "clear" command i get
```No such command in 3.6.4 of python ```
How to fix?

Edit: why do i have clear on shims?

```
$ which clear
/home/qwexvf/.asdf/shims/clear
```

Thanks.

**Comment by tuvistavie** [comment]
I have no idea where the `clear` command would come from. If you run `cat /home/qwexvf/.asdf/shims/clear`, there should be a line with the Python version. You can then check in `~/.asdf/installs/python/VERSION/bin` what kind of command is clear.
Although I do not think that asdf-python has anything to do with this, please let me know when you find out.

**Comment by qwexvf** [comment]
@tuvistavie sorry, sounds like it was anaconda's problem i reinstalled asdf-python and reinstalled python 3.6.5 everything worked fine.
Not sure what went wrong with anaconda.

Thanks for you help tho!!

**Comment by devxpy** [comment]
Related - https://github.com/ContinuumIO/anaconda-issues/issues/331

**Comment by devxpy** [comment]
@danhper I still have this issue.

It only happens when I try to use python versions other than anaconda. FWIW, pyenv doesn't seem to have this issue.

**Comment by linwownil** [comment]
I am still experiencing this issue with `miniconda3-3.11-23.5.0-3` installed in `asdf`. Using:

    mv $HOME/.asdf/shims/clear $HOME/.asdf/shims/clear_old

allowed me to clear my terminal again
