### ISSUE TITLE
When removing Python plugin shims are not destroyed

### ISSUE THREAD

**Issue by teddy-error** [tuvistavie/asdf-python#6]
This causes shims that would otherwise not exist to block the path to installations of python in later directories. Expected behavior would be for plugin-removal to delete these 'null-ptr' executables, allowing installations outside of asdf to execute. Instead the user will execute the invalid shims, receiving an error message 'No such plugin'.

**Comment by tuvistavie** [comment]
Hi, thanks for the feedback.
This is not directly related to this plugin, but rather to asdf itself.
We are planning to work on a solution for this, as soon as we find the time to.
Please check https://github.com/asdf-vm/asdf/issues/67 for more information.
