### ISSUE TITLE
Using asdf's python with python-gst

### ISSUE THREAD

**Issue by johnhamelink** [tuvistavie/asdf-python#7]
Hi there,

I'm trying to follow the installation process for installing [Mopidy](https://docs.mopidy.com/en/latest/installation/source/) from source using my python build from asdf. One key element of the process is the installation of `python-gst-1.0` in ubuntu (or `gst-python2` for me on Arch). How would I install this package within the context of asdf so I can run the program?

```
[john:~] 7s % mopidy
Traceback (most recent call last):
  File "/home/john/.asdf/installs/python/2.7.12/bin/mopidy", line 7, in <module>
    from mopidy.__main__ import main
  File "/home/john/.asdf/installs/python/2.7.12/lib/python2.7/site-packages/mopidy/__main__.py", line 8, in <module>
    from mopidy.internal.gi import Gst  # noqa: F401
  File "/home/john/.asdf/installs/python/2.7.12/lib/python2.7/site-packages/mopidy/internal/gi.py", line 9, in <module>
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'
```

**Comment by tuvistavie** [comment]
Hi, sorry for the delay.
Would using the system python be a solution for you?
While it is not yet possible, we are planning to add this feature to asdf.

**Comment by johnhamelink** [comment]
@tuvistavie no problem. That's what I ended up doing :smile:

**Comment by tuvistavie** [comment]
The issue is getting quite old, but asdf now supports `system` version, so this should not be an issue anymore.
