### ISSUE TITLE
SyntaxError when executing `python -c`

### ISSUE THREAD

**Issue by lebedev-yury** [tuvistavie/asdf-python#8]
Hello!

I have a weird problem here (not sure it's `asdf-python` issue though):

```bash
$ /usr/bin/python --version
$ ~/.asdf/shims/python --version

$ /usr/bin/python -c 'import sys; print("python")'
python

$ ~/.asdf/shims/python -c 'import sys; print("python")'
  File "<string>", line 1
    import
         ^
SyntaxError: invalid syntax
```

I would simply ignore this, but `anaconda-mode` in spacemacs is using `-c` to evaluate code, and throws an error every time I type something in a python file in spacemacs.

**Comment by tuvistavie** [comment]
Hi, I will take a look at it!

**Comment by tuvistavie** [comment]
This should now be fixed, could you try to run

```
asdf plugin-update python
``` 

and give it another try?

**Comment by lebedev-yury** [comment]
@tuvistavie thanks! will give it a try now.

**Comment by lebedev-yury** [comment]
@tuvistavie thank you, it's working after reinstalling python through asdf
